{
 "title": "sidekiq",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queue size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" }
     ],
     "measurement": "sidekiq_queues",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Other statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_stat",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "stat" ], "type": "tag" }
     ],
     "measurement": "sidekiq_stats",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stat", "operator": "<>", "value": "processed" },
      { "condition": "AND", "key": "stat", "operator": "<>", "value": "processes_size" },
      { "condition": "AND", "key": "stat", "operator": "<>", "value": "workers_size" }
     ]
    }
   ]
  },
  {
   "title": "Processed, failed and dead",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_stat",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "stat" ], "type": "tag" }
     ],
     "measurement": "sidekiq_stats",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "stat", "operator": "=", "value": "processed" },
      { "condition": "OR", "key": "stat", "operator": "=", "value": "failed" },
      { "condition": "OR", "key": "stat", "operator": "=", "value": "dead_size" }
     ]
    }
   ]
  },
  {
   "title": "Size processes and workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_stat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "stat" ], "type": "tag" }
     ],
     "measurement": "sidekiq_stats",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "stat", "operator": "=", "value": "workers_size" },
      { "condition": "OR", "key": "stat", "operator": "=", "value": "processes_size" }
     ]
    }
   ]
  },
  {
   "title": "Long waiting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_class",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "class" ], "type": "tag" }
     ],
     "measurement": "sidekiq_jobs",
     "select": [
      [
       { "params": [ "waited" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Long run",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_class",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "class" ], "type": "tag" }
     ],
     "measurement": "sidekiq_jobs",
     "select": [
      [
       { "params": [ "worked" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_class",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "class" ], "type": "tag" }
     ],
     "measurement": "sidekiq_jobs",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "finish" }
     ]
    }
   ]
  },
  {
   "title": "Fallen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_class",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "class" ], "type": "tag" }
     ],
     "measurement": "sidekiq_jobs",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "error" }
     ]
    }
   ]
  }
 ]
}